# Generated by Django 3.2.6 on 2021-08-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='subject',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
