# Generated by Django 3.2.6 on 2021-08-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0003_auto_20210808_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ManyToManyField(to='cbt.Subject'),
        ),
    ]
