# Generated by Django 3.2.6 on 2021-08-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0004_auto_20210808_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled',
            field=models.ManyToManyField(to='cbt.Student'),
        ),
    ]
